version: "3.5"

services:
  postgres:
    container_name: ppostgres.Technesis
    image: "postgres:15-alpine"
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "127.0.0.1:8764:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ubnfhf
      POSTGRES_DB: Technesis_db
    volumes:
      - "ppostgres.postgres.data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: Technesis_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: miha@mial.ru
      PGADMIN_DEFAULT_PASSWORD: ubnfhf
    ports:
      - "5055:80"
    depends_on:
      - postgres
  
  bot:
    build: ../Technesis_bot
    container_name: bot_1
    restart: always
    command: >
      bash -c "alembic upgrade head
      && alembic revision --autogenerate
      && alembic upgrade head
      && python main.py"
    env_file:
      - .env


volumes:
  ppostgres.postgres.data: {}
